---

- hosts: localhost
  vars:
    nios_provider:
      host: 10.60.27.4
      username: admin
      password: infoblox

  connection: local
  tasks:
   - name: create NAPTR record
     nios_naptr_record:
       name: '*.subscriber-100.ansiblezone.com'
       order: 1000 
       preference: 10
       replacement: replacement1.network.ansiblezone.com
       state: present
       provider: "{{ nios_provider }}"
