---

- hosts: localhost
  vars:
    nios_provider:
      host: 10.60.27.4
      username: admin
      password: infoblox

  connection: local
  tasks:
   - name: delete host record
     nios_host_record:
       name: host.ansiblezone.com
       view: ansibleDnsView
       state: absent
       provider: "{{ nios_provider }}"
